### ISSUE TITLE
SyntaxError: Unexpected token 'B', "Billing ha"... is not valid JSON

### ISSUE THREAD

**Issue by ShivankK26** [konhito/AI_IMAGE-GENERATION#2]
Facing this error while making API request. Can you please help @konhito. How did you solve it?

![Image](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/520db5e8-e0a8-4484-a470-a342f78cd326)

**Comment by konhito** [comment]
share me your code

**Comment by ShivankK26** [comment]
which part do you want?

**Comment by konhito** [comment]
everything

**Comment by ShivankK26** [comment]
Give me a minute I'll upload it on github

**Comment by ShivankK26** [comment]
There was some issue while uploading the repo so i've made 2 repos.
**CLIENT SIDE:**
https://github.com/ShivankK26/AI-Image-Generator-App

**SERVER SIDE:**
https://github.com/ShivankK26/AI-APP

**Comment by konhito** [comment]
ok im checking the issue

**Comment by ShivankK26** [comment]
Okay. Thanks a lot!

**Comment by konhito** [comment]
its working fine for me
![Screenshot from 2023-06-04 12-14-40](https://github.com/konhito/AI_IMAGE-GENERATION/assets/132154862/f9813245-89a5-4d1c-b39b-db7e5c4294db)
![Screenshot from 2023-06-04 12-15-06](https://github.com/konhito/AI_IMAGE-GENERATION/assets/132154862/94ca8e62-73ea-450f-97aa-ea39f3c45268)
use my server file and do npm i and make .env
![Screenshot from 2023-06-04 12-17-09](https://github.com/konhito/AI_IMAGE-GENERATION/assets/132154862/c5a27915-1e82-4f1c-8d35-06e3c42ca4d7)
make sure mongo db is connected and on mongodb got to networks then do this so anyone can connect to your server 
![Screenshot from 2023-06-04 12-19-33](https://github.com/konhito/AI_IMAGE-GENERATION/assets/132154862/4792750f-461c-4de7-b51f-055d66fe80ef)

**Comment by ShivankK26** [comment]
my server file as in?
I didn't get it

**Comment by ShivankK26** [comment]
I also have a .env file and I've added the GPT API link to it.

**Comment by konhito** [comment]
i mean i dont have ur .env fle so i used "my server file"(from my project)...u can use yours

**Comment by ShivankK26** [comment]
Okay.

**Comment by ShivankK26** [comment]
But i'm still getting error..

**Comment by konhito** [comment]
on your terminal monondb is connected right?

**Comment by ShivankK26** [comment]
yes

**Comment by konhito** [comment]
![Screenshot from 2023-06-04 12-29-34](https://github.com/konhito/AI_IMAGE-GENERATION/assets/132154862/4db9bbc6-5132-48e8-93d9-41805a95da63)

**Comment by ShivankK26** [comment]
haha..lol

**Comment by ShivankK26** [comment]
I've just connected mongoDB using the atlas link and used it in my .env file..nothing else...is this right?

**Comment by konhito** [comment]
change network access on mongodb

**Comment by ShivankK26** [comment]
how to do it?

**Comment by konhito** [comment]
cuz ur ip changes everday

**Comment by ShivankK26** [comment]
ohkk

**Comment by konhito** [comment]
![Screenshot from 2023-06-04 12-19-33](https://github.com/konhito/AI_IMAGE-GENERATION/assets/132154862/647838fa-fbd3-4378-9efa-a337d026e04e)

**Comment by ShivankK26** [comment]
yup, did it.

**Comment by ShivankK26** [comment]
what next?

**Comment by konhito** [comment]
still getting error?

**Comment by ShivankK26** [comment]
![Screenshot 2023-06-04 at 12 36 05 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/4dcb9016-7bb3-4f2b-97ca-8cfcc1faf1a0)

**Comment by ShivankK26** [comment]
ya man it is still showing the same error

**Comment by konhito** [comment]
send me your terminal photo

**Comment by ShivankK26** [comment]
okay

**Comment by ShivankK26** [comment]
![Screenshot 2023-06-04 at 12 38 27 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/fa65b2e9-503f-446a-b009-a97083dafee3)

![Screenshot 2023-06-04 at 12 38 38 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/6aebb7e0-602d-4d02-b9b0-6fe38f2f3ea0)

![Screenshot 2023-06-04 at 12 38 49 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/f17eafa8-190d-40cd-bf44-284ebff61326)



![Screenshot 2023-06-04 at 12 38 49 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/22b0703c-756b-47d1-90f2-09df773e6abb)
![Screenshot 2023-06-04 at 12 38 55 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/3fcc7f4a-e9c1-4e2c-815c-5cde037d3928)
![Screenshot 2023-06-04 at 12 39 01 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/e5448a50-2fce-4f57-a575-a478bd09a5a0)

![Screenshot 2023-06-04 at 12 39 07 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/554e6b93-ce2b-4e9d-a80b-12fccf7adf6e)
![Screenshot 2023-06-04 at 12 39 12 PM](https://github.com/konhito/AI_IMAGE-GENERATION/assets/115289871/d271f99f-ae17-4f09-9c59-e0ff60f8bddf)

**Comment by konhito** [comment]
w8 u have installed axios right?

**Comment by ShivankK26** [comment]
no

**Comment by konhito** [comment]
wow dude

**Comment by konhito** [comment]
follow the video

**Comment by ShivankK26** [comment]
i think i missed it..could you please tell me the commands to install it?

**Comment by konhito** [comment]
i dont remember exactly but npm install axios this shoud be working

**Comment by ShivankK26** [comment]
ohkk..and i should run this in client dir or server one?

**Comment by konhito** [comment]
a.... server i guess

**Comment by ShivankK26** [comment]
did it...but it's showing error again...huhh

**Comment by konhito** [comment]
its beyond my expertise...sorry i cant help u

**Comment by ShivankK26** [comment]
Okay, no issues. Thank you so much for your time and efforts!

**Comment by konhito** [comment]
![Screenshot from 2023-06-04 12-56-56](https://github.com/konhito/AI_IMAGE-GENERATION/assets/132154862/92abbbd4-38be-47cb-b0b6-191ff396ac25)
 ok

**Comment by ShivankK26** [comment]
If you're available anytime. Can we discuss this issue over call?

**Comment by ShivankK26** [comment]
I mean Gmeet

**Comment by ShivankK26** [comment]
Cause i'm not able to get it..also i'm a beginner in fullstack projects like these.
